#pragma once

enum BuffTypesEnum { PHYSICAL_DAMAGE_BUFF = 0, PHYSICAL_DEFENSE_BUFF = 1, MAGIC_DAMAGE_BUFF = 2, MAGIC_DEFENSE_BUFF = 3, SPEED_BUFF = 4, EVASION_BUFF = 5, STAMINA_BUFF = 6, HP_BUFF = 7, MANA_BUFF = 8, STRENGHT_BUFF = 9, AGILITY_BUFF = 10, INTELIGENCE_BUFF = 11 };